# Generated by Django 4.0.2 on 2022-02-17 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('tipo_pesca', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SkillsPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('percentage_required', models.CharField(max_length=128)),
                ('qtde_points', models.CharField(max_length=128)),
                ('utility_level', models.CharField(max_length=128)),
                ('habilidades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.habilidades')),
            ],
        ),
    ]
