# Generated by Django 4.0.2 on 2022-02-17 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mapas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peixe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=128)),
                ('trophy', models.IntegerField()),
                ('super_trophy', models.IntegerField()),
                ('temperatura_ideal', models.IntegerField()),
                ('condicoes', models.CharField(max_length=128)),
                ('time_list', models.CharField(max_length=128)),
                ('mapa', models.ManyToManyField(to='mapas.Mapas')),
            ],
        ),
    ]
