# Generated by Django 4.0.2 on 2022-02-17 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('level', models.IntegerField()),
                ('descricao', models.CharField(max_length=2048)),
                ('habilidades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.habilidades')),
            ],
        ),
    ]
