# Generated by Django 4.0.2 on 2022-02-17 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mapas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('base', models.CharField(max_length=128)),
                ('aditivo1', models.CharField(max_length=128)),
                ('aditivo2', models.CharField(max_length=128)),
                ('aditivo3', models.CharField(max_length=128)),
                ('aditivo4', models.CharField(max_length=128)),
                ('engodo', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='MisturaSeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mistura', models.CharField(max_length=128)),
                ('aditivo1', models.CharField(max_length=128)),
                ('aditivo2', models.CharField(max_length=128)),
                ('aditivo3', models.CharField(max_length=128)),
                ('aditivo4', models.CharField(max_length=128)),
                ('atrativo', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Pva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('mapa', models.ManyToManyField(to='mapas.Mapas')),
                ('mistura_seca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misturas.misturaseca')),
            ],
        ),
    ]
