# Generated by Django 4.0.2 on 2022-02-17 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mapas', '0001_initial'),
        ('misturas', '0001_initial'),
        ('peixes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pva',
            name='peixes',
            field=models.ManyToManyField(to='peixes.Peixe'),
        ),
        migrations.AddField(
            model_name='gb',
            name='mapa',
            field=models.ManyToManyField(to='mapas.Mapas'),
        ),
        migrations.AddField(
            model_name='gb',
            name='peixes',
            field=models.ManyToManyField(to='peixes.Peixe'),
        ),
    ]
